"commit_message": "Fixed: New translations %original_file_name% from Crowdin"

"files": [
  {
    "source" : "/lang/en/**/*.php",
    # https://developer.crowdin.com/configuration-file/#placeholders
    "translation" : "/lang/%locale%/**/%original_file_name%"
  }
]
