"commit_message": "Fixed: New translations %original_file_name% from Crowdin"

"files": [
  {
    "source" : "/lang/en/**/*.php",
    "translation" : "/lang/%two_letters_code%/**/%original_file_name%"
  }
]
